/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BoardId = IDL.Text;
export const OperationType = IDL.Variant({
  'fillColor' : IDL.Null,
  'moveShape' : IDL.Null,
  'draw' : IDL.Null,
  'erase' : IDL.Null,
  'addText' : IDL.Null,
  'clearBoard' : IDL.Null,
  'editText' : IDL.Null,
  'addShape' : IDL.Null,
});
export const Color = IDL.Record({
  'a' : IDL.Nat8,
  'b' : IDL.Nat8,
  'g' : IDL.Nat8,
  'r' : IDL.Nat8,
});
export const ShapeType = IDL.Variant({
  'ellipse' : IDL.Null,
  'polygon' : IDL.Null,
  'rectangle' : IDL.Null,
  'line' : IDL.Null,
  'circle' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Position = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
export const Area = IDL.Record({
  'bottomRight' : Position,
  'topLeft' : Position,
});
export const Payload = IDL.Variant({
  'fillColor' : IDL.Record({ 'area' : Area, 'color' : Color }),
  'moveShape' : IDL.Record({ 'shapeId' : IDL.Text, 'newPosition' : Position }),
  'draw' : IDL.Null,
  'erase' : IDL.Null,
  'addText' : IDL.Record({ 'text' : IDL.Text, 'position' : Position }),
  'clearBoard' : IDL.Null,
  'editText' : IDL.Record({ 'textId' : IDL.Text, 'newText' : IDL.Text }),
  'addShape' : IDL.Record({
    'color' : Color,
    'size' : IDL.Nat,
    'shape' : ShapeType,
    'position' : Position,
  }),
});
export const Operation = IDL.Record({
  'opType' : OperationType,
  'color' : IDL.Opt(Color),
  'size' : IDL.Opt(IDL.Nat),
  'text' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
  'shape' : IDL.Opt(ShapeType),
  'timestamp' : Timestamp,
  'position' : Position,
  'payload' : Payload,
});
export const Version = IDL.Nat;
export const BoardBackground = IDL.Variant({
  'dots' : IDL.Null,
  'grid' : IDL.Null,
  'lines' : IDL.Null,
  'blank' : IDL.Null,
});

export const idlService = IDL.Service({
  'appendOperation' : IDL.Func([BoardId, Operation], [Version], []),
  'clearBoard' : IDL.Func([BoardId], [Version], []),
  'createBoard' : IDL.Func([BoardId, BoardBackground], [], []),
  'getBoardBackground' : IDL.Func(
      [BoardId],
      [IDL.Opt(BoardBackground)],
      ['query'],
    ),
  'getBoardContent' : IDL.Func(
      [BoardId],
      [
        IDL.Opt(
          IDL.Record({
            'background' : BoardBackground,
            'version' : Version,
            'operations' : IDL.Vec(Operation),
          })
        ),
      ],
      ['query'],
    ),
  'getBoardSnapshot' : IDL.Func(
      [BoardId],
      [
        IDL.Opt(
          IDL.Record({
            'background' : BoardBackground,
            'version' : Version,
            'operations' : IDL.Vec(Operation),
          })
        ),
      ],
      ['query'],
    ),
  'getBoardVersion' : IDL.Func([BoardId], [IDL.Opt(Version)], ['query']),
  'getChangesSinceVersion' : IDL.Func(
      [BoardId, Version],
      [
        IDL.Opt(
          IDL.Record({
            'background' : BoardBackground,
            'version' : Version,
            'operations' : IDL.Vec(Operation),
          })
        ),
      ],
      ['query'],
    ),
  'updateBoardBackground' : IDL.Func([BoardId, BoardBackground], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BoardId = IDL.Text;
  const OperationType = IDL.Variant({
    'fillColor' : IDL.Null,
    'moveShape' : IDL.Null,
    'draw' : IDL.Null,
    'erase' : IDL.Null,
    'addText' : IDL.Null,
    'clearBoard' : IDL.Null,
    'editText' : IDL.Null,
    'addShape' : IDL.Null,
  });
  const Color = IDL.Record({
    'a' : IDL.Nat8,
    'b' : IDL.Nat8,
    'g' : IDL.Nat8,
    'r' : IDL.Nat8,
  });
  const ShapeType = IDL.Variant({
    'ellipse' : IDL.Null,
    'polygon' : IDL.Null,
    'rectangle' : IDL.Null,
    'line' : IDL.Null,
    'circle' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Position = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
  const Area = IDL.Record({ 'bottomRight' : Position, 'topLeft' : Position });
  const Payload = IDL.Variant({
    'fillColor' : IDL.Record({ 'area' : Area, 'color' : Color }),
    'moveShape' : IDL.Record({
      'shapeId' : IDL.Text,
      'newPosition' : Position,
    }),
    'draw' : IDL.Null,
    'erase' : IDL.Null,
    'addText' : IDL.Record({ 'text' : IDL.Text, 'position' : Position }),
    'clearBoard' : IDL.Null,
    'editText' : IDL.Record({ 'textId' : IDL.Text, 'newText' : IDL.Text }),
    'addShape' : IDL.Record({
      'color' : Color,
      'size' : IDL.Nat,
      'shape' : ShapeType,
      'position' : Position,
    }),
  });
  const Operation = IDL.Record({
    'opType' : OperationType,
    'color' : IDL.Opt(Color),
    'size' : IDL.Opt(IDL.Nat),
    'text' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
    'shape' : IDL.Opt(ShapeType),
    'timestamp' : Timestamp,
    'position' : Position,
    'payload' : Payload,
  });
  const Version = IDL.Nat;
  const BoardBackground = IDL.Variant({
    'dots' : IDL.Null,
    'grid' : IDL.Null,
    'lines' : IDL.Null,
    'blank' : IDL.Null,
  });
  
  return IDL.Service({
    'appendOperation' : IDL.Func([BoardId, Operation], [Version], []),
    'clearBoard' : IDL.Func([BoardId], [Version], []),
    'createBoard' : IDL.Func([BoardId, BoardBackground], [], []),
    'getBoardBackground' : IDL.Func(
        [BoardId],
        [IDL.Opt(BoardBackground)],
        ['query'],
      ),
    'getBoardContent' : IDL.Func(
        [BoardId],
        [
          IDL.Opt(
            IDL.Record({
              'background' : BoardBackground,
              'version' : Version,
              'operations' : IDL.Vec(Operation),
            })
          ),
        ],
        ['query'],
      ),
    'getBoardSnapshot' : IDL.Func(
        [BoardId],
        [
          IDL.Opt(
            IDL.Record({
              'background' : BoardBackground,
              'version' : Version,
              'operations' : IDL.Vec(Operation),
            })
          ),
        ],
        ['query'],
      ),
    'getBoardVersion' : IDL.Func([BoardId], [IDL.Opt(Version)], ['query']),
    'getChangesSinceVersion' : IDL.Func(
        [BoardId, Version],
        [
          IDL.Opt(
            IDL.Record({
              'background' : BoardBackground,
              'version' : Version,
              'operations' : IDL.Vec(Operation),
            })
          ),
        ],
        ['query'],
      ),
    'updateBoardBackground' : IDL.Func([BoardId, BoardBackground], [], []),
  });
};

export const init = ({ IDL }) => { return []; };