/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Area { 'bottomRight' : Position, 'topLeft' : Position }
export type BoardBackground = { 'dots' : null } |
  { 'grid' : null } |
  { 'lines' : null } |
  { 'blank' : null };
export type BoardId = string;
export interface Color {
  'a' : number,
  'b' : number,
  'g' : number,
  'r' : number,
}
export interface Operation {
  'opType' : OperationType,
  'color' : [] | [Color],
  'size' : [] | [bigint],
  'text' : [] | [string],
  'author' : Principal,
  'shape' : [] | [ShapeType],
  'timestamp' : Timestamp,
  'position' : Position,
  'payload' : Payload,
}
export type OperationType = { 'fillColor' : null } |
  { 'moveShape' : null } |
  { 'draw' : null } |
  { 'erase' : null } |
  { 'addText' : null } |
  { 'clearBoard' : null } |
  { 'editText' : null } |
  { 'addShape' : null };
export type Payload = { 'fillColor' : { 'area' : Area, 'color' : Color } } |
  { 'moveShape' : { 'shapeId' : string, 'newPosition' : Position } } |
  { 'draw' : null } |
  { 'erase' : null } |
  { 'addText' : { 'text' : string, 'position' : Position } } |
  { 'clearBoard' : null } |
  { 'editText' : { 'textId' : string, 'newText' : string } } |
  {
    'addShape' : {
      'color' : Color,
      'size' : bigint,
      'shape' : ShapeType,
      'position' : Position,
    }
  };
export interface Position { 'x' : bigint, 'y' : bigint }
export type ShapeType = { 'ellipse' : null } |
  { 'polygon' : null } |
  { 'rectangle' : null } |
  { 'line' : null } |
  { 'circle' : null };
export type Timestamp = bigint;
export type Version = bigint;
export interface _SERVICE {
  'appendOperation' : ActorMethod<[BoardId, Operation], Version>,
  'clearBoard' : ActorMethod<[BoardId], Version>,
  'createBoard' : ActorMethod<[BoardId, BoardBackground], undefined>,
  'getBoardBackground' : ActorMethod<[BoardId], [] | [BoardBackground]>,
  'getBoardContent' : ActorMethod<
    [BoardId],
    [] | [
      {
        'background' : BoardBackground,
        'version' : Version,
        'operations' : Array<Operation>,
      }
    ]
  >,
  'getBoardSnapshot' : ActorMethod<
    [BoardId],
    [] | [
      {
        'background' : BoardBackground,
        'version' : Version,
        'operations' : Array<Operation>,
      }
    ]
  >,
  'getBoardVersion' : ActorMethod<[BoardId], [] | [Version]>,
  'getChangesSinceVersion' : ActorMethod<
    [BoardId, Version],
    [] | [
      {
        'background' : BoardBackground,
        'version' : Version,
        'operations' : Array<Operation>,
      }
    ]
  >,
  'updateBoardBackground' : ActorMethod<[BoardId, BoardBackground], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];