/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Operation {
    opType: OperationType;
    color?: Color;
    size?: bigint;
    text?: string;
    author: Principal;
    shape?: ShapeType;
    timestamp: Timestamp;
    position: Position;
    payload: Payload;
}
export type Timestamp = bigint;
export interface Position {
    x: bigint;
    y: bigint;
}
export type Payload = {
    __kind__: "fillColor";
    fillColor: {
        area: Area;
        color: Color;
    };
} | {
    __kind__: "moveShape";
    moveShape: {
        shapeId: string;
        newPosition: Position;
    };
} | {
    __kind__: "draw";
    draw: null;
} | {
    __kind__: "erase";
    erase: null;
} | {
    __kind__: "addText";
    addText: {
        text: string;
        position: Position;
    };
} | {
    __kind__: "clearBoard";
    clearBoard: null;
} | {
    __kind__: "editText";
    editText: {
        textId: string;
        newText: string;
    };
} | {
    __kind__: "addShape";
    addShape: {
        color: Color;
        size: bigint;
        shape: ShapeType;
        position: Position;
    };
};
export interface Area {
    bottomRight: Position;
    topLeft: Position;
}
export type Version = bigint;
export interface Color {
    a: number;
    b: number;
    g: number;
    r: number;
}
export type BoardId = string;
export enum BoardBackground {
    dots = "dots",
    grid = "grid",
    lines = "lines",
    blank = "blank"
}
export enum OperationType {
    fillColor = "fillColor",
    moveShape = "moveShape",
    draw = "draw",
    erase = "erase",
    addText = "addText",
    clearBoard = "clearBoard",
    editText = "editText",
    addShape = "addShape"
}
export enum ShapeType {
    ellipse = "ellipse",
    polygon = "polygon",
    rectangle = "rectangle",
    line = "line",
    circle = "circle"
}
export interface backendInterface {
    appendOperation(boardId: BoardId, op: Operation): Promise<Version>;
    clearBoard(boardId: BoardId): Promise<Version>;
    createBoard(boardId: BoardId, background: BoardBackground): Promise<void>;
    getBoardBackground(boardId: BoardId): Promise<BoardBackground | null>;
    getBoardContent(boardId: BoardId): Promise<{
        background: BoardBackground;
        version: Version;
        operations: Array<Operation>;
    } | null>;
    getBoardSnapshot(boardId: BoardId): Promise<{
        background: BoardBackground;
        version: Version;
        operations: Array<Operation>;
    } | null>;
    getBoardVersion(boardId: BoardId): Promise<Version | null>;
    getChangesSinceVersion(boardId: BoardId, clientVersion: Version): Promise<{
        background: BoardBackground;
        version: Version;
        operations: Array<Operation>;
    } | null>;
    updateBoardBackground(boardId: BoardId, background: BoardBackground): Promise<void>;
}
import type { Area as _Area, BoardBackground as _BoardBackground, Color as _Color, Operation as _Operation, OperationType as _OperationType, Payload as _Payload, Position as _Position, ShapeType as _ShapeType, Timestamp as _Timestamp, Version as _Version } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async appendOperation(arg0: BoardId, arg1: Operation): Promise<Version> {
        if (this.processError) {
            try {
                const result = await this.actor.appendOperation(arg0, to_candid_Operation_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appendOperation(arg0, to_candid_Operation_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearBoard(arg0: BoardId): Promise<Version> {
        if (this.processError) {
            try {
                const result = await this.actor.clearBoard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearBoard(arg0);
            return result;
        }
    }
    async createBoard(arg0: BoardId, arg1: BoardBackground): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBoard(arg0, to_candid_BoardBackground_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBoard(arg0, to_candid_BoardBackground_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getBoardBackground(arg0: BoardId): Promise<BoardBackground | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardBackground(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardBackground(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoardContent(arg0: BoardId): Promise<{
        background: BoardBackground;
        version: Version;
        operations: Array<Operation>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardContent(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardContent(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoardSnapshot(arg0: BoardId): Promise<{
        background: BoardBackground;
        version: Version;
        operations: Array<Operation>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardSnapshot(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardSnapshot(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoardVersion(arg0: BoardId): Promise<Version | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardVersion(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardVersion(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChangesSinceVersion(arg0: BoardId, arg1: Version): Promise<{
        background: BoardBackground;
        version: Version;
        operations: Array<Operation>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangesSinceVersion(arg0, arg1);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangesSinceVersion(arg0, arg1);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBoardBackground(arg0: BoardId, arg1: BoardBackground): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBoardBackground(arg0, to_candid_BoardBackground_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBoardBackground(arg0, to_candid_BoardBackground_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BoardBackground_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BoardBackground): BoardBackground {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_OperationType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OperationType): OperationType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Operation_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Operation): Operation {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Payload_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payload): Payload {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ShapeType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShapeType): ShapeType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BoardBackground]): BoardBackground | null {
    return value.length === 0 ? null : from_candid_BoardBackground_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        background: _BoardBackground;
        version: _Version;
        operations: Array<_Operation>;
    }]): {
    background: BoardBackground;
    version: Version;
    operations: Array<Operation>;
} | null {
    return value.length === 0 ? null : from_candid_record_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Color]): Color | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShapeType]): ShapeType | null {
    return value.length === 0 ? null : from_candid_ShapeType_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Version]): Version | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    background: _BoardBackground;
    version: _Version;
    operations: Array<_Operation>;
}): {
    background: BoardBackground;
    version: Version;
    operations: Array<Operation>;
} {
    return {
        background: from_candid_BoardBackground_n13(_uploadFile, _downloadFile, value.background),
        version: value.version,
        operations: from_candid_vec_n17(_uploadFile, _downloadFile, value.operations)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    opType: _OperationType;
    color: [] | [_Color];
    size: [] | [bigint];
    text: [] | [string];
    author: Principal;
    shape: [] | [_ShapeType];
    timestamp: _Timestamp;
    position: _Position;
    payload: _Payload;
}): {
    opType: OperationType;
    color?: Color;
    size?: bigint;
    text?: string;
    author: Principal;
    shape?: ShapeType;
    timestamp: Timestamp;
    position: Position;
    payload: Payload;
} {
    return {
        opType: from_candid_OperationType_n20(_uploadFile, _downloadFile, value.opType),
        color: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.color)),
        size: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.size)),
        text: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.text)),
        author: value.author,
        shape: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.shape)),
        timestamp: value.timestamp,
        position: value.position,
        payload: from_candid_Payload_n28(_uploadFile, _downloadFile, value.payload)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: _Color;
    size: bigint;
    shape: _ShapeType;
    position: _Position;
}): {
    color: Color;
    size: bigint;
    shape: ShapeType;
    position: Position;
} {
    return {
        color: value.color,
        size: value.size,
        shape: from_candid_ShapeType_n26(_uploadFile, _downloadFile, value.shape),
        position: value.position
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dots: null;
} | {
    grid: null;
} | {
    lines: null;
} | {
    blank: null;
}): BoardBackground {
    return "dots" in value ? BoardBackground.dots : "grid" in value ? BoardBackground.grid : "lines" in value ? BoardBackground.lines : "blank" in value ? BoardBackground.blank : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fillColor: null;
} | {
    moveShape: null;
} | {
    draw: null;
} | {
    erase: null;
} | {
    addText: null;
} | {
    clearBoard: null;
} | {
    editText: null;
} | {
    addShape: null;
}): OperationType {
    return "fillColor" in value ? OperationType.fillColor : "moveShape" in value ? OperationType.moveShape : "draw" in value ? OperationType.draw : "erase" in value ? OperationType.erase : "addText" in value ? OperationType.addText : "clearBoard" in value ? OperationType.clearBoard : "editText" in value ? OperationType.editText : "addShape" in value ? OperationType.addShape : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ellipse: null;
} | {
    polygon: null;
} | {
    rectangle: null;
} | {
    line: null;
} | {
    circle: null;
}): ShapeType {
    return "ellipse" in value ? ShapeType.ellipse : "polygon" in value ? ShapeType.polygon : "rectangle" in value ? ShapeType.rectangle : "line" in value ? ShapeType.line : "circle" in value ? ShapeType.circle : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fillColor: {
        area: _Area;
        color: _Color;
    };
} | {
    moveShape: {
        shapeId: string;
        newPosition: _Position;
    };
} | {
    draw: null;
} | {
    erase: null;
} | {
    addText: {
        text: string;
        position: _Position;
    };
} | {
    clearBoard: null;
} | {
    editText: {
        textId: string;
        newText: string;
    };
} | {
    addShape: {
        color: _Color;
        size: bigint;
        shape: _ShapeType;
        position: _Position;
    };
}): {
    __kind__: "fillColor";
    fillColor: {
        area: Area;
        color: Color;
    };
} | {
    __kind__: "moveShape";
    moveShape: {
        shapeId: string;
        newPosition: Position;
    };
} | {
    __kind__: "draw";
    draw: null;
} | {
    __kind__: "erase";
    erase: null;
} | {
    __kind__: "addText";
    addText: {
        text: string;
        position: Position;
    };
} | {
    __kind__: "clearBoard";
    clearBoard: null;
} | {
    __kind__: "editText";
    editText: {
        textId: string;
        newText: string;
    };
} | {
    __kind__: "addShape";
    addShape: {
        color: Color;
        size: bigint;
        shape: ShapeType;
        position: Position;
    };
} {
    return "fillColor" in value ? {
        __kind__: "fillColor",
        fillColor: value.fillColor
    } : "moveShape" in value ? {
        __kind__: "moveShape",
        moveShape: value.moveShape
    } : "draw" in value ? {
        __kind__: "draw",
        draw: value.draw
    } : "erase" in value ? {
        __kind__: "erase",
        erase: value.erase
    } : "addText" in value ? {
        __kind__: "addText",
        addText: value.addText
    } : "clearBoard" in value ? {
        __kind__: "clearBoard",
        clearBoard: value.clearBoard
    } : "editText" in value ? {
        __kind__: "editText",
        editText: value.editText
    } : "addShape" in value ? {
        __kind__: "addShape",
        addShape: from_candid_record_n30(_uploadFile, _downloadFile, value.addShape)
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Operation>): Array<Operation> {
    return value.map((x)=>from_candid_Operation_n18(_uploadFile, _downloadFile, x));
}
function to_candid_BoardBackground_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BoardBackground): _BoardBackground {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_OperationType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OperationType): _OperationType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Operation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Operation): _Operation {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Payload_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payload): _Payload {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ShapeType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShapeType): _ShapeType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    opType: OperationType;
    color?: Color;
    size?: bigint;
    text?: string;
    author: Principal;
    shape?: ShapeType;
    timestamp: Timestamp;
    position: Position;
    payload: Payload;
}): {
    opType: _OperationType;
    color: [] | [_Color];
    size: [] | [bigint];
    text: [] | [string];
    author: Principal;
    shape: [] | [_ShapeType];
    timestamp: _Timestamp;
    position: _Position;
    payload: _Payload;
} {
    return {
        opType: to_candid_OperationType_n3(_uploadFile, _downloadFile, value.opType),
        color: value.color ? candid_some(value.color) : candid_none(),
        size: value.size ? candid_some(value.size) : candid_none(),
        text: value.text ? candid_some(value.text) : candid_none(),
        author: value.author,
        shape: value.shape ? candid_some(to_candid_ShapeType_n5(_uploadFile, _downloadFile, value.shape)) : candid_none(),
        timestamp: value.timestamp,
        position: value.position,
        payload: to_candid_Payload_n7(_uploadFile, _downloadFile, value.payload)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: Color;
    size: bigint;
    shape: ShapeType;
    position: Position;
}): {
    color: _Color;
    size: bigint;
    shape: _ShapeType;
    position: _Position;
} {
    return {
        color: value.color,
        size: value.size,
        shape: to_candid_ShapeType_n5(_uploadFile, _downloadFile, value.shape),
        position: value.position
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BoardBackground): {
    dots: null;
} | {
    grid: null;
} | {
    lines: null;
} | {
    blank: null;
} {
    return value == BoardBackground.dots ? {
        dots: null
    } : value == BoardBackground.grid ? {
        grid: null
    } : value == BoardBackground.lines ? {
        lines: null
    } : value == BoardBackground.blank ? {
        blank: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OperationType): {
    fillColor: null;
} | {
    moveShape: null;
} | {
    draw: null;
} | {
    erase: null;
} | {
    addText: null;
} | {
    clearBoard: null;
} | {
    editText: null;
} | {
    addShape: null;
} {
    return value == OperationType.fillColor ? {
        fillColor: null
    } : value == OperationType.moveShape ? {
        moveShape: null
    } : value == OperationType.draw ? {
        draw: null
    } : value == OperationType.erase ? {
        erase: null
    } : value == OperationType.addText ? {
        addText: null
    } : value == OperationType.clearBoard ? {
        clearBoard: null
    } : value == OperationType.editText ? {
        editText: null
    } : value == OperationType.addShape ? {
        addShape: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShapeType): {
    ellipse: null;
} | {
    polygon: null;
} | {
    rectangle: null;
} | {
    line: null;
} | {
    circle: null;
} {
    return value == ShapeType.ellipse ? {
        ellipse: null
    } : value == ShapeType.polygon ? {
        polygon: null
    } : value == ShapeType.rectangle ? {
        rectangle: null
    } : value == ShapeType.line ? {
        line: null
    } : value == ShapeType.circle ? {
        circle: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "fillColor";
    fillColor: {
        area: Area;
        color: Color;
    };
} | {
    __kind__: "moveShape";
    moveShape: {
        shapeId: string;
        newPosition: Position;
    };
} | {
    __kind__: "draw";
    draw: null;
} | {
    __kind__: "erase";
    erase: null;
} | {
    __kind__: "addText";
    addText: {
        text: string;
        position: Position;
    };
} | {
    __kind__: "clearBoard";
    clearBoard: null;
} | {
    __kind__: "editText";
    editText: {
        textId: string;
        newText: string;
    };
} | {
    __kind__: "addShape";
    addShape: {
        color: Color;
        size: bigint;
        shape: ShapeType;
        position: Position;
    };
}): {
    fillColor: {
        area: _Area;
        color: _Color;
    };
} | {
    moveShape: {
        shapeId: string;
        newPosition: _Position;
    };
} | {
    draw: null;
} | {
    erase: null;
} | {
    addText: {
        text: string;
        position: _Position;
    };
} | {
    clearBoard: null;
} | {
    editText: {
        textId: string;
        newText: string;
    };
} | {
    addShape: {
        color: _Color;
        size: bigint;
        shape: _ShapeType;
        position: _Position;
    };
} {
    return value.__kind__ === "fillColor" ? {
        fillColor: value.fillColor
    } : value.__kind__ === "moveShape" ? {
        moveShape: value.moveShape
    } : value.__kind__ === "draw" ? {
        draw: value.draw
    } : value.__kind__ === "erase" ? {
        erase: value.erase
    } : value.__kind__ === "addText" ? {
        addText: value.addText
    } : value.__kind__ === "clearBoard" ? {
        clearBoard: value.clearBoard
    } : value.__kind__ === "editText" ? {
        editText: value.editText
    } : value.__kind__ === "addShape" ? {
        addShape: to_candid_record_n9(_uploadFile, _downloadFile, value.addShape)
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
